import { useMemo, useState } from 'react';
import { branches, images } from '../data/siteData';
import { branchTypeName, formatPhone } from '../../../shared/utils/formatters';

export default function LocationsSection({ onBook }) {
  const [city, setCity] = useState('all');
  const [type, setType] = useState('all');
  const filteredBranches = useMemo(() => branches.map((branch, index) => ({ branch, index })).filter(({ branch }) => (city === 'all' || branch.city === city) && (type === 'all' || branch.type === type || branch.type === 'both')), [city, type]);
  const showMusicLocations = () => { setCity('all'); setType('music'); window.setTimeout(() => document.getElementById('locations')?.scrollIntoView({ behavior: 'smooth' }), 0); };
  return <><section className="music-banner"><img src={images.musicBanner} alt="Không gian Music Box GenZ" loading="lazy" /><div className="music-banner-shade"></div><div className="music-banner-copy reveal"><p className="eyebrow">GENZ MUSIC / TURN IT UP</p><h2>Hội bạn đủ mặt.<br /><span>Playlist đủ cháy.</span></h2><button className="button cyan" onClick={showMusicLocations}>Tìm không gian Music <span>↗</span></button></div><span className="sound-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span></section><section id="locations" className="section locations"><div className="section-heading reveal"><div><p className="eyebrow">04 / SEE YOU AT GENZ</p><h2>Gần bạn.<br /><span className="muted">Đúng vibe.</span></h2></div><p>Chọn nơi hẹn. Gọi một cuộc.<br />Cuộc vui bắt đầu từ đây.</p></div><div className="location-tools"><div className="filters" role="group" aria-label="Lọc thành phố">{[['all', 'Tất cả'], ['hn', 'Hà Nội'], ['hcm', 'TP. Hồ Chí Minh']].map(([value, label]) => <button key={value} className={city === value ? 'active' : ''} onClick={() => setCity(value)} aria-pressed={city === value}>{label}</button>)}</div><label className="type-filter"><span>Mô hình</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">Tất cả mô hình</option><option value="cinema">Cinema</option><option value="music">Music / GenZ Box</option></select></label></div><div className="location-summary" aria-live="polite">{filteredBranches.length} địa điểm phù hợp</div><div className="location-list">{filteredBranches.map(({ branch, index }) => <article className="location" key={`${branch.name}-${branch.phone}`}><div><span className="branch-type">{branch.city === 'hn' ? 'HÀ NỘI' : 'TP. HỒ CHÍ MINH'} / {branchTypeName(branch.type)}</span><h3>GenZ {branch.name}</h3><p>{branch.address}</p><div className="location-links"><a href={`tel:${branch.phone}`}>{formatPhone(branch.phone)}</a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`GenZ ${branch.address}`)}`} target="_blank" rel="noopener noreferrer" aria-label={`Chỉ đường đến GenZ ${branch.name}`}>Chỉ đường ↗</a></div></div><button className="branch-book" onClick={() => onBook(index)} aria-label={`Đặt phòng tại GenZ ${branch.name}`}>↗</button></article>)}</div><p className="location-note">Tên địa chỉ được giữ theo danh sách cơ sở cung cấp. Vui lòng gọi chi nhánh để xác nhận phòng trống, tiện ích và địa chỉ trước khi đến.</p></section></>;
}

